import type { Product } from '@/schemas/product.schema';
import { MOCK_STORE_ID } from '@/config/mock.config';

// Importa todas las imágenes de productos como URLs resueltas por Vite
const imageModules: Record<string, string> = import.meta.glob(
  '@/assets/productsImage/*.{jpg,jpeg,png,webp,avif,gif}',
  { eager: true, import: 'default', query: '?url' },
) as Record<string, string>;
const imageUrls: string[] = Object.values(imageModules);

/** Asigna una imagen rotativa del pool de assets al producto por índice */
function getImageForIndex(index: number): string | null {
  if (imageUrls.length === 0) return null;
  return imageUrls[index % imageUrls.length];
}

/**
 * Datos de ejemplo que conforman exactamente al tipo Product (Zod).
 * Cada producto tiene su imagen asignada en el campo `image` del schema.
 * Todos los nombres están en mayúsculas.
 */
export const PRODUCTOS_EJEMPLO: Product[] = [
  {
    id: '1',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(0),
    name: 'AVON SWEET HONESTY',
    barcode: '7909189182596',
    categoryId: 'Higiene Personal',
    supplierId: 'Avon',
    costPrice: 3000,
    salePrice: 4200,
    profitMargin: 40,
    stock: 12,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-02-15'),
    updatedAt: new Date('2025-03-10'),
  },
  {
    id: '2',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(1),
    name: 'AGUA MINERAL VILLAVICENCIO',
    barcode: '7790580120149',
    categoryId: 'Bebidas',
    supplierId: 'Danone',
    costPrice: 700,
    salePrice: 980,
    profitMargin: 40,
    stock: 40,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-01-20'),
    updatedAt: new Date('2025-02-28'),
  },
  {
    id: '3',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(2),
    name: 'DETERGENTE MAGISTRAL',
    barcode: '7791234567890',
    categoryId: 'Limpieza',
    supplierId: 'Unilever',
    costPrice: 1500,
    salePrice: 2100,
    profitMargin: 40,
    stock: 3,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-03-01'),
    updatedAt: new Date('2025-03-15'),
  },
  {
    id: '4',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(3),
    name: 'LECHE LA SERENÍSIMA',
    barcode: '7790580120156',
    categoryId: 'Lácteos',
    supplierId: 'Mastellone',
    costPrice: 800,
    salePrice: 1120,
    profitMargin: 40,
    stock: 0,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-02-10'),
    updatedAt: new Date('2025-03-05'),
  },
  {
    id: '5',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(4),
    name: 'COCA-COLA 2.25L',
    barcode: '7790895000058',
    categoryId: 'Bebidas',
    supplierId: 'Coca-Cola',
    costPrice: 1200,
    salePrice: 1700,
    profitMargin: 42,
    stock: 25,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-01-05'),
    updatedAt: new Date('2025-03-18'),
  },
  {
    id: '6',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(5),
    name: 'JABÓN EN POLVO ALA',
    barcode: '7791234000111',
    categoryId: 'Limpieza',
    supplierId: 'Unilever',
    costPrice: 2200,
    salePrice: 3100,
    profitMargin: 41,
    stock: 8,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-02-20'),
    updatedAt: new Date('2025-03-12'),
  },
  {
    id: '7',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(6),
    name: 'GALLETITAS OREO',
    barcode: '7790580003456',
    categoryId: 'Alimentos',
    supplierId: 'Mondelez',
    costPrice: 600,
    salePrice: 850,
    profitMargin: 42,
    stock: 0,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date('2025-03-01'),
  },
  {
    id: '8',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(7),
    name: 'FIDEOS MATARAZZO',
    barcode: '7790570007890',
    categoryId: 'Alimentos',
    supplierId: 'Molinos Río de la Plata',
    costPrice: 450,
    salePrice: 650,
    profitMargin: 44,
    stock: 15,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-03-20'),
    updatedAt: new Date('2025-03-20'),
  },
  {
    id: '9',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(8),
    name: 'YERBA MATE PLAYADITO 1KG',
    barcode: '7793704000012',
    categoryId: 'Alimentos',
    supplierId: 'Playadito',
    costPrice: 3200,
    salePrice: 4500,
    profitMargin: 41,
    stock: 18,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-02-11'),
    updatedAt: new Date('2025-03-17'),
  },
  {
    id: '10',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(9),
    name: 'AZÚCAR LEDESMA 1KG',
    barcode: '7792540001123',
    categoryId: 'Alimentos',
    supplierId: 'Ledesma',
    costPrice: 900,
    salePrice: 1250,
    profitMargin: 39,
    stock: 22,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-01-25'),
    updatedAt: new Date('2025-03-02'),
  },
  {
    id: '11',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(10),
    name: 'ACEITE COCINERO 900ML',
    barcode: '7790060004451',
    categoryId: 'Alimentos',
    supplierId: 'Molinos Río de la Plata',
    costPrice: 2100,
    salePrice: 2950,
    profitMargin: 40,
    stock: 9,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-02-08'),
    updatedAt: new Date('2025-03-11'),
  },
  {
    id: '12',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(11),
    name: 'ARROZ GALLO ORO 1KG',
    barcode: '7791122003344',
    categoryId: 'Alimentos',
    supplierId: 'Gallo',
    costPrice: 1100,
    salePrice: 1550,
    profitMargin: 41,
    stock: 14,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-02-17'),
    updatedAt: new Date('2025-03-09'),
  },
  {
    id: '13',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(12),
    name: 'HARINA PUREZA 000 1KG',
    barcode: '7792180002217',
    categoryId: 'Alimentos',
    supplierId: 'Molinos Cañuelas',
    costPrice: 780,
    salePrice: 1100,
    profitMargin: 41,
    stock: 28,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-01-30'),
    updatedAt: new Date('2025-03-04'),
  },
  {
    id: '14',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(13),
    name: 'MAYONESA HELLMANN\'S 500G',
    barcode: '7794000965432',
    categoryId: 'Alimentos',
    supplierId: 'Unilever',
    costPrice: 1450,
    salePrice: 2050,
    profitMargin: 41,
    stock: 7,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-02-22'),
    updatedAt: new Date('2025-03-13'),
  },
  {
    id: '15',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(14),
    name: 'KETCHUP HEINZ 397G',
    barcode: '7791239988771',
    categoryId: 'Alimentos',
    supplierId: 'Heinz',
    costPrice: 1700,
    salePrice: 2400,
    profitMargin: 41,
    stock: 6,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-03-03'),
    updatedAt: new Date('2025-03-16'),
  },
  {
    id: '16',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(15),
    name: 'SAL FINA CELUSAL 500G',
    barcode: '7790107001236',
    categoryId: 'Alimentos',
    supplierId: 'Celusal',
    costPrice: 500,
    salePrice: 720,
    profitMargin: 44,
    stock: 19,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-01-18'),
    updatedAt: new Date('2025-03-01'),
  },
  {
    id: '17',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(16),
    name: 'LECHE CHOCOLATADA CINDOR 1L',
    barcode: '7793940005567',
    categoryId: 'Lácteos',
    supplierId: 'Danone',
    costPrice: 1400,
    salePrice: 1950,
    profitMargin: 39,
    stock: 11,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-02-19'),
    updatedAt: new Date('2025-03-14'),
  },
  {
    id: '18',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(17),
    name: 'YOGUR BEBIBLE SER 1L',
    barcode: '7791337006678',
    categoryId: 'Lácteos',
    supplierId: 'La Serenísima',
    costPrice: 1600,
    salePrice: 2250,
    profitMargin: 41,
    stock: 5,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-02-28'),
    updatedAt: new Date('2025-03-18'),
  },
  {
    id: '19',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(18),
    name: 'QUESO CREMA CASANCREM 290G',
    barcode: '7798176004325',
    categoryId: 'Lácteos',
    supplierId: 'La Serenísima',
    costPrice: 1900,
    salePrice: 2700,
    profitMargin: 42,
    stock: 4,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-02-05'),
    updatedAt: new Date('2025-03-07'),
  },
  {
    id: '20',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(19),
    name: 'MANTECA SANCOR 200G',
    barcode: '7790080012345',
    categoryId: 'Lácteos',
    supplierId: 'Sancor',
    costPrice: 1750,
    salePrice: 2480,
    profitMargin: 42,
    stock: 0,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-01-22'),
    updatedAt: new Date('2025-03-06'),
  },
  {
    id: '21',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(20),
    name: 'GASEOSA SPRITE 2.25L',
    barcode: '7790895000065',
    categoryId: 'Bebidas',
    supplierId: 'Coca-Cola',
    costPrice: 1150,
    salePrice: 1650,
    profitMargin: 43,
    stock: 17,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-01-27'),
    updatedAt: new Date('2025-03-15'),
  },
  {
    id: '22',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(21),
    name: 'JUGO CEPITA NARANJA 1L',
    barcode: '7790895643210',
    categoryId: 'Bebidas',
    supplierId: 'Cepita',
    costPrice: 1050,
    salePrice: 1480,
    profitMargin: 41,
    stock: 13,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-02-01'),
    updatedAt: new Date('2025-03-12'),
  },
  {
    id: '23',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(22),
    name: 'CERVEZA QUILMES 1L',
    barcode: '7792798001004',
    categoryId: 'Bebidas',
    supplierId: 'Quilmes',
    costPrice: 1800,
    salePrice: 2550,
    profitMargin: 42,
    stock: 10,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-01-12'),
    updatedAt: new Date('2025-03-10'),
  },
  {
    id: '24',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(23),
    name: 'ENERGIZANTE SPEED 473ML',
    barcode: '7798119220011',
    categoryId: 'Bebidas',
    supplierId: 'Speed',
    costPrice: 1300,
    salePrice: 1850,
    profitMargin: 42,
    stock: 16,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-02-25'),
    updatedAt: new Date('2025-03-17'),
  },
  {
    id: '25',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(24),
    name: 'LAVANDINA AYUDÍN 1L',
    barcode: '7793253002210',
    categoryId: 'Limpieza',
    supplierId: 'Ayudín',
    costPrice: 950,
    salePrice: 1350,
    profitMargin: 42,
    stock: 21,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-02-06'),
    updatedAt: new Date('2025-03-08'),
  },
  {
    id: '26',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(25),
    name: 'SUAVIZANTE COMFORT 900ML',
    barcode: '7791290011122',
    categoryId: 'Limpieza',
    supplierId: 'Unilever',
    costPrice: 1700,
    salePrice: 2400,
    profitMargin: 41,
    stock: 9,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-02-12'),
    updatedAt: new Date('2025-03-11'),
  },
  {
    id: '27',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(26),
    name: 'ESPONJA MORTIMER',
    barcode: '7794444555667',
    categoryId: 'Limpieza',
    supplierId: 'Mortimer',
    costPrice: 350,
    salePrice: 520,
    profitMargin: 49,
    stock: 30,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-01-19'),
    updatedAt: new Date('2025-03-03'),
  },
  {
    id: '28',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(27),
    name: 'LIMPIAVIDRIOS CIF 500ML',
    barcode: '7791290789001',
    categoryId: 'Limpieza',
    supplierId: 'Unilever',
    costPrice: 1250,
    salePrice: 1780,
    profitMargin: 42,
    stock: 12,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-03-04'),
    updatedAt: new Date('2025-03-18'),
  },
  {
    id: '29',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(28),
    name: 'SHAMPOO SEDAL 340ML',
    barcode: '7791293021112',
    categoryId: 'Higiene Personal',
    supplierId: 'Unilever',
    costPrice: 2100,
    salePrice: 2950,
    profitMargin: 40,
    stock: 14,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-02-07'),
    updatedAt: new Date('2025-03-13'),
  },
  {
    id: '30',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(29),
    name: 'ACONDICIONADOR PANTENE 400ML',
    barcode: '7500435012345',
    categoryId: 'Higiene Personal',
    supplierId: 'P&G',
    costPrice: 2600,
    salePrice: 3650,
    profitMargin: 40,
    stock: 10,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-02-16'),
    updatedAt: new Date('2025-03-15'),
  },
  {
    id: '31',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(30),
    name: 'DESODORANTE REXONA MEN',
    barcode: '7791293045678',
    categoryId: 'Higiene Personal',
    supplierId: 'Unilever',
    costPrice: 1800,
    salePrice: 2550,
    profitMargin: 42,
    stock: 7,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-01-28'),
    updatedAt: new Date('2025-03-09'),
  },
  {
    id: '32',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(31),
    name: 'PASTA DENTAL COLGATE TOTAL',
    barcode: '7891024132211',
    categoryId: 'Higiene Personal',
    supplierId: 'Colgate',
    costPrice: 1450,
    salePrice: 2050,
    profitMargin: 41,
    stock: 20,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-02-03'),
    updatedAt: new Date('2025-03-10'),
  },
  {
    id: '33',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(32),
    name: 'PAPEL HIGIÉNICO ELITE 4 ROLLOS',
    barcode: '7790250007766',
    categoryId: 'Higiene Personal',
    supplierId: 'Elite',
    costPrice: 1900,
    salePrice: 2680,
    profitMargin: 41,
    stock: 23,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-01-17'),
    updatedAt: new Date('2025-03-05'),
  },
  {
    id: '34',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(33),
    name: 'TOALLITAS FEMENINAS ALWAYS',
    barcode: '7501001112349',
    categoryId: 'Higiene Personal',
    supplierId: 'P&G',
    costPrice: 1600,
    salePrice: 2280,
    profitMargin: 43,
    stock: 11,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-02-18'),
    updatedAt: new Date('2025-03-14'),
  },
  {
    id: '35',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(34),
    name: 'CHOCOLATE MILKA 55G',
    barcode: '7622210449281',
    categoryId: 'Golosinas',
    supplierId: 'Mondelez',
    costPrice: 700,
    salePrice: 980,
    profitMargin: 40,
    stock: 26,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-01-09'),
    updatedAt: new Date('2025-03-07'),
  },
  {
    id: '36',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(35),
    name: 'ALFAJOR JORGITO',
    barcode: '7791118000019',
    categoryId: 'Golosinas',
    supplierId: 'Jorgito',
    costPrice: 400,
    salePrice: 580,
    profitMargin: 45,
    stock: 35,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-01-14'),
    updatedAt: new Date('2025-03-03'),
  },
  {
    id: '37',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(36),
    name: 'CARAMELOS SUGUS',
    barcode: '7790580509876',
    categoryId: 'Golosinas',
    supplierId: 'Arcor',
    costPrice: 300,
    salePrice: 450,
    profitMargin: 50,
    stock: 50,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-01-11'),
    updatedAt: new Date('2025-03-01'),
  },
  {
    id: '38',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(37),
    name: 'PAPAS FRITAS LAYS CLÁSICAS',
    barcode: '7790310004567',
    categoryId: 'Snacks',
    supplierId: 'PepsiCo',
    costPrice: 950,
    salePrice: 1380,
    profitMargin: 45,
    stock: 18,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-02-09'),
    updatedAt: new Date('2025-03-08'),
  },
  {
    id: '39',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(38),
    name: 'PALITOS SALADOS PEHUAMAR',
    barcode: '7792180009981',
    categoryId: 'Snacks',
    supplierId: 'PepsiCo',
    costPrice: 800,
    salePrice: 1150,
    profitMargin: 44,
    stock: 16,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-02-14'),
    updatedAt: new Date('2025-03-09'),
  },
  {
    id: '40',
    storeId: MOCK_STORE_ID,
    image: getImageForIndex(39),
    name: 'CAFÉ INSTANTÁNEO DOLCA 170G',
    barcode: '7794000598765',
    categoryId: 'Alimentos',
    supplierId: 'Nestlé',
    costPrice: 3400,
    salePrice: 4750,
    profitMargin: 40,
    stock: 8,
    minStock: 5,
    unit: 'UNIT',
    allowDecimalQuantity: false,
    isDeleted: false,
    createdAt: new Date('2025-02-21'),
    updatedAt: new Date('2025-03-16'),
  },
];